//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaFabio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabecalhoNFE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CabecalhoNFE()
        {
            this.CorpoNFE = new HashSet<CorpoNFE>();
        }
    
        public int Id { get; set; }
        public string NumNF { get; set; }
        public Nullable<int> Id_for { get; set; }
        public string TipoNFE { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<System.TimeSpan> HoraEntrada { get; set; }
    
        public virtual Fornecedores Fornecedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorpoNFE> CorpoNFE { get; set; }
    }
}
