//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvaFabio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produtos()
        {
            this.CorpoNFE = new HashSet<CorpoNFE>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public string Descricao { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public Nullable<decimal> CustoIni { get; set; }
        public Nullable<decimal> CustoAtu { get; set; }
        public string OBS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorpoNFE> CorpoNFE { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
